var fruits = ["apple", "banana", "orange"];
console.log(fruits[0]);
console.log(fruits.length);
var skills = [];
skills[0] = "problem solving";
skills[1] = "programming";
skills.push("Software Design");
console.log(skills);
skills.pop();
console.log(skills);
